---
- name: gathering OS related information
  hosts: all
  tasks:
    - name: os info
      debug:
        msg: "{{item}}"
      with_items:
        - "{{ansible_distribution}}"
        - "{{ansible_distribution_version}}"
        - "{{ansible_distribution_major_version}}"

