---
- name: installing packages on group of hosts
  hosts: jenkins_server
  gather_facts: false
  become: yes
  tasks:
    - name: installing jenkins server
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: "{{a}}",b: "{{b}}",c: "{{c}}"}
        - {a: "{{d}}",b: "{{b}}",c: "{{e}}"}
        - {a: "{{f}}",b: "{{b}}",c: "{{e}}"} 
    - name: installing jenkins file
      get_url:
        url: https://get.jenkins.io/war-stable/2.387.2/jenkins.war
        dest: /home/ubuntu      
