---
- name: implementing handlers
  hosts: all
  tasks:
    - name: installing apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: check url response
    - name: editing the index file
      copy:
        content: "welcome to my page"
        dest: /var/www/html/index.html
      notify: restart service
  handlers:    
    - name: restart service
      service:
        name: apache2
        state: restarted
    - name: check url response
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.89.7
        - http://172.31.93.90

