---
- name: configuring tomcat9
  hosts: all
  tasks:
    - name: installing tomcat9
      apt:
        name: tomcat9
        state: present
        update_cache: yes
    - name: installing tomcat9-admin
      apt:
        name: tomcat9-admin
        state: present

    - name: edit the tomcat-users.xml
      copy:
        src: /home/ubuntu/tomcat-users.xml
        dest: /etc/tomcat9
    - name: replcing the port with 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat9/server.xml
    - name: restating the service
      service:
        name: tomcat9
        state: restarted
    - name: pause for 1min
      pause:
        minutes: 1
    - name: check the url response from server1
      uri:
        url: http://172.31.93.90:9090
        status_code: 200
    - name: check the url response for server2
      uri:
        url: http://44.201.125.68:9090
    - name: deleteing the package
      apt:
        name: tomcat9
        state: absent
        purge: yes
    - name: deleting the package
      apt:
        name: tomcat9-admin
        state: absent
        purge: yes
