---
- name: check for a folder f1  if it not present create a file f1
  hosts: all
  tasks:
    - name: check for folder f1
      stat:
        path: /home/ubuntu/f1
      register: result
    - name: displaying sbove output of above module
      debug:
        var: result
    - name: create a file f1 , if f1 dir is not present
      file:
        name: /home/ubuntu/f1
        state: touch
      when: result.stat.exists == false
